name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 680651984289.dkr.ecr.eu-west-1.amazonaws.com
          username: ${{ vars.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      -
        name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: 680651984289.dkr.ecr.eu-west-1.amazonaws.com/weg21/colour-picker:latest



    
